### ISSUE TITLE
version check outdated

### ISSUE THREAD

**Issue by XoHydroX** [BryceCanyonCounty/bcc-housing#20]
Have the lastest version tryied fixxing it on my end but i think it has to do on ur end maybe not sure 
would love it to says updated for when we restart server we know when its outdated 

[    script:bcc-utils] (CACHED)❌Outdated! [bcc-housing] (Version 1.0.4)
[    script:bcc-utils] NEW VERSION (1.04) <https://github.com/BryceCanyonCounty/bcc-housing/releases/tag/1.04>
[    script:bcc-utils] CHANGELOG
[    script:bcc-utils] ## What's Changed
[    script:bcc-utils] * Update manageHouseMenu.lua in https://github.com/BryceCanyonCounty/bcc-housing/pull/11
[    script:bcc-utils] * vorp_menuConversion by @jakeyboi1 in https://github.com/BryceCanyonCounty/bcc-housing/pull/12
[    script:bcc-utils] * Update manageHouseMenu.lua in https://github.com/BryceCanyonCounty/bcc-housing/pull/13
[    script:bcc-utils] * Adding interior maps by @AndrewR3K in https://github.com/BryceCanyonCounty/bcc-housing/pull/15
[    script:bcc-utils] * Create  fr_lang.lua by @elzetia in https://github.com/BryceCanyonCounty/bcc-housing/pull/16
[    script:bcc-utils] * create ro_lang.lua by @iseeyoucopy in https://github.com/BryceCanyonCounty/bcc-housing/pull/17
[    script:bcc-utils] * restruct by @jakeyboi1 in https://github.com/BryceCanyonCounty/bcc-housing/pull/18
[    script:bcc-utils]
[    script:bcc-utils] ## New Contributors
[    script:bcc-utils] * @AndrewR3K made their first contribution in https://github.com/BryceCanyonCounty/bcc-housing/pull/15
[    script:bcc-utils] * @elzetia made their first contribution in https://github.com/BryceCanyonCounty/bcc-housing/pull/16
[    script:bcc-utils] * @iseeyoucopy made their first contribution in https://github.com/BryceCanyonCounty/bcc-housing/pull/17
[    script:bcc-utils]
[    script:bcc-utils] **Full Changelog**: https://github.com/BryceCanyonCounty/bcc-housing/compare/1.0.3...1.04

**Comment by DavFount** [comment]
Check the fx manifest. As long as that version matches the latest version you're fine to ignore.

Or you can try clearing your server cache. Seems like that's what's being used.

**Comment by XoHydroX** [comment]
Yea I tried all that don’t work we do love ur scripts I hope the outdated
error be fixed next updates
