### ISSUE TITLE
cant add furniture to houses 

### ISSUE THREAD

**Issue by yaboibutt3r** [BryceCanyonCounty/bcc-housing#28]
no error shows on live console but f8 console throws error. 
script:bcc-housing Error: Invalid furniture type 'shelf' available types are... and it does it with every furniture type

**Comment by iseeyoucopy** [comment]
You can find a fix in here

https://github.com/BryceCanyonCounty/bcc-housing/pull/27/commits/4e7eeeaad6a7d28f35be8ef69a0be23bd979abcb
