### ISSUE TITLE
two errors

### ISSUE THREAD

**Issue by yaboibutt3r** [BryceCanyonCounty/bcc-housing#33]
updated to most recent release and got two issues 
[ citizen-server-impl] Could not make hard link for /bcc-housing/stream//Siddin3.ymap <-> gta5-fivem-txadmin/VORPCore_5B98CF.base/cache/files/bcc-housing/stream_cache/zcf9d4755e8556e77f64c320335d3ee6dfa1c5735. 
and 
[  script:bcc-housing] SCRIPT ERROR: @bcc-housing/server/helpers/functions.lua:78: attempt to call a nil value (global 'DelSpawnedFurn')
[  script:bcc-housing] > handler (@bcc-housing/server/helpers/functions.lua:78)
[  script:bcc-housing] SCRIPT ERROR: @bcc-housing/server/helpers/functions.lua:78: attempt to call a nil value (global 'DelSpawnedFurn')
[  script:bcc-housing] > handler (@bcc-housing/server/helpers/functions.lua:78)

**Comment by iseeyoucopy** [comment]
I forgot to add a file for furniture, you can find a fix in here #34
