### ISSUE TITLE
Collide with doorlock?

### ISSUE THREAD

**Issue by Troublemaker141** [BryceCanyonCounty/bcc-housing#4]
Hey,
the system seems like a great work.
But how is it supposed to work with bcc-doorlocks?
Creating a door closes the create house window.
And with then created doors the owner and ppl with enter permissions cant interact.

Btw is it planned that ppl can buy premade houses?

Best regards.

**Comment by axdevelopment** [comment]
same issue here

**Comment by MehonTheMan** [comment]
You can check that but since one of the updates it should work all fine now
